# Generated by Django 4.2 on 2025-06-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='page',
            field=models.CharField(choices=[('home', 'Home Page'), ('presentation_design', 'Presentation Design'), ('graphics', 'Graphics & Print Design'), ('other_services', 'Other Services')], default='home', max_length=50),
            preserve_default=False,
        ),
    ]
