# Generated by Django 4.2 on 2025-06-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_faq_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='content',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='profile_image',
            field=models.ImageField(default='testimonials/profile_images/pro.svg', upload_to='testimonials/profile_images/'),
        ),
    ]
