# Generated by Django 4.2 on 2025-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_testimonials_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='team/images/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('dribbble', models.URLField(blank=True, null=True)),
                ('group', models.URLField(blank=True, null=True)),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('COO', 'COO'), ('CTO', 'CTO'), ('DESIGNER', 'Designer'), ('PRESENTATION_EXPERT', 'Presentation Expert'), ('MEMBER', 'Team Member'), ('OTHER', 'Other')], default='MEMBER', max_length=50)),
                ('priority', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='profile_image',
            field=models.ImageField(default='testimonials/profile_images/pro.png', upload_to='testimonials/profile_images/'),
        ),
    ]
