# Generated by Django 4.2 on 2025-06-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
