# Generated by Django 4.2 on 2025-06-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_testimonials_is_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('date', models.DateField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='content',
            field=models.TextField(max_length=400),
        ),
    ]
